### PR TITLE
Support for non-standard data directories.

### PR DESCRIPTION
**Pull request by n15g**
Should fix a couple of issues raised here: https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/53

* No longer crashes the extension if directories are missing.
* No longer assumes the default model folders and takes the location from the runtime config.
* Fixed issue with empty embeddings list on startup when sd_hijack/TI loads later than this extension.
* get_X_dirs() is now get_X_dir() as underlying platform doesn't seem to allow multiple directories for models and can lead to an inconsistency between what the platform believes are the total set of model files and what the extension does.

I couldn't see a use-case for the multiple directory scanning within the extension given that the platform only allows a single data directory per model-type. Let me know if there's a reason for that multiplicity and I'll update to add it back in.

### CODE REVIEW

**Comment by CurtisDS** [comment]
thanks, sorry been away for the week.

I will go over this now, but one thing I'm hesitant about is "No longer assumes the default model folders and takes the location from the runtime config." ...it did take the location from the run time config before (or at least it should have been) but it was also adding the default locations. This way people could put their model files outside the install directory and their preview files in the default folders to avoid the issues that come with putting your files outside the install directory. I get that I might not have been checking if the directory existed before accessing it.... but beyond that I dont see why someone would have an issue with having extra options.

But I will get back to you after I look over the code.

**Comment by CurtisDS** [comment]
So, after looking over the code... yes there is a reason I was adding in the default directories on top of the directories set in the config.

As I half explained earlier, the webserver only serves content from within the install directory. So if you set the paths in the config for your models to something outside of the a1111 install directory the extension needs to do some extra work to try and support that (like converting image previews and HTML pages to base64 strings instead of linking to the files directly). There is some basic support for having your preview files outside of the a1111 install directory but it can make things more complicated specifically with HTML and Markdown preview files if you want to link to other local files like images, etc.

Lets say you have this set up:

```cmd
/model/lora/mymodel.safetensors
/model/lora/myModelPreview/mymodel.html
/model/lora/myModelPreview/filelinkedtofromHTMLpreview.file
```

where the mymodel.html file has an internal link to filelinkedtofromHTMLpreview.file. If the myModelPreview folder is inside the a1111 directory it will work as expected. But if its outside of the a1111 directory it will not be able to locate filelinkedtofromHTMLpreview.file because when I convert the html file to base64 it doesn't dig through the code to also convert anything the page links to. Meaning filelinkedtofromHTMLpreview.file isn't being served up by the web server and thus will be inaccessible.

So a way to fix that was to allow the preview files to be put in the default directory regardless of where your config says the actual model is located.

Its a bit of a niche use case but that's why I don't just use the directory from the config alone.

I do agree I should have been checking to see if the folder existed before adding it to the list. I thought I was tbh, but I guess not.

So if you want to adjust that I will merge the pull request or I can just manually add in the embedding fix and the directory checks myself. Either way thanks for your contributions and sorry it took so long for me to look at this.

**Comment by n15g** [comment]
No problems, and that makes sense. I had a feeling it might be something like that, but opted to go the nuclear route to start with, since having multiple directories can lead to weird scenarios where previews will load from both, but models will only load from one... but anyone in that situation has put themselves there intentionally 😂

It's probably neater if I close this PR off and you cherry-pick those changes, but let me know if you want me to raise another with just those two fixes.

**Comment by CurtisDS** [comment]
Yea its an odd behaviour but I couldn't think of any better way to do get around the file server being limited to the a1111 install directory.

I'll just add the lines myself and push later tonight, but thank you again.

**Pull request closed without merging**
